name: Update README

on:
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Generar actividad reciente en el README
      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@v2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Commit y push de los cambios
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated recent activity"
          git push
