name: Update README

on:
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
  update-readme:
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v3
